### ISSUE TITLE
*Mark as spam* feature

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-webmail#18]
_From @tonioo on December 4, 2013 15:45_

**Originally created by Antoine Nguyen on 2012-10-21T10:14:07Z**

Let webmail users tell amavis about _false negatives_.

_Copied from original issue: tonioo/modoboa#332_

**Comment by bakelnaar** [comment]
It has been a while since there has been any comment on this thread. Is there any timeline in which it is to be expected that this feature will be implemented?
This feature would be greatly appreciated, since it would mean that every user will be able to contribute to the quality of the spam filtering.

This implementation for Roundcube might be useful to use as a basis:
https://github.com/JohnDoh/Roundcube-Plugin-Mark-as-Junk-2

**Comment by tonioo** [comment]
There is no timeline defined yet but this roundcube plugin is indeed a
good start. I was thinking about a simple button to move the message to
the Junk folder. The dovecot antispam plugin would do the rest.

Calling sa-learn is another interesting option, need to think about it.
Have you check the amavis plugin and its learning features?

**Comment by bakelnaar** [comment]
To be honest I'm new to Modoboa. Therefore, assuming you mean the Modoboa plugin for amavis, unfortunately I must disappoint you.

If you mean the Spamassassin plugin for amavis, then amavis just uses spamassassin in the background, so sa-learn -spam works. I assume you're already using sa-learn -ham for messages you move out of quarantaine to the inbox and sa-learn -spam for mails you delete, so my guess would be that it would be a straightforward implementation.
The other option as far as I can see (not implementing sa-learn) would be to scan all the Junk folders regularly and hope that users don't remove the mail in the meanwhile. This would be less reliable and also cause more load on the host.

Looking further into the problem, the solution would be to duplicate the 'move to trash' button to a 'mark as spam' button and add the sa-learn -spam call to it. Personally I would prefer the mail to be deleted permanently instead of moved to the Junk folder (for me this folder is just for improper marked mail), but for me the most important would be to have the function to mark mail as spam and get it out of my inbox.

Unfortunately I don't have any experience with Django as a programming language. However, if it is needed I could look into an implementation.

**Comment by tonioo** [comment]
Actually, the quarantine and the webmail don't communicate yet. It is
possible to release a message from the quarantine using the PDP protocol
and there are also shortcuts to learn spam/ham using sa-learn. It is
possible to do global learning (amavis user when sa-learn is called),
per-domain learning or user-level learning. Those levels can be
enabled/disabled from Modoboa but are linked to the amavis plugin.

The webmail plugin could indeed call sa-learn but it would create a
dependency with the amavis plugin (because we can't assume
amavis/spamassassin are present and confugured if this plugin is not
installed).

What's your opinion?

**Comment by bakelnaar** [comment]
It indeed would create a dependency on the amavis plugin (I'm still getting familiar with the modoboa structure, so excuse me for that).

Would it be a possibility to implement it as a cross-dependency (i.e. only show the button in the case the amavis plugin is enabled)? To avoid problems with the amavis configuration, it could be implemented as a call to the amavis plugin, which then decides what to do with the request based on the configuration.

Another option would be to move all the 'marked as spam' mail to a pre-specified folder, which then would be checked regularly (daily / hourly) by the amavis plugin if present. This method would not have my preference, but should be working.

**Comment by tonioo** [comment]
I'll think about it. I guess the best option is to implement a
driver-based behaviour: default one would be to move messages to a
pre-defined folder, another one would be to call sa-learn if the amavis
plugin is in place.

**Comment by bakelnaar** [comment]
One thought on the pre-defined folder: it might be useful to make it possible to change the folder location from the settings panel. For the rest I agree with the driver-based approach.

**Comment by tonioo** [comment]
@bakelnaar So I implemented the "move to folder" option as a quick win. I'll work on the driver-based approach later.

**Comment by bakelnaar** [comment]
Thanks, I'll look into it soon.
