### ISSUE TITLE
Webmail Error: "Modoboa: command UID => got more than 10000 bytes"

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-webmail#4]
_From @piwats on November 17, 2014 14:16_

Hello,

suddenly, when trying to access the INBOX in the Webamiler under 1.1.7 I am getting this error:

```Modoboa: command UID => got more than 10000 bytes```

No emails are being shown in the list apart from this error.

Also I get nor errors in my log when this happens...

-Paul

Some information: http://stackoverflow.com/questions/25457441/reading-emails-with-imaplib-got-more-than-10000-bytes-error

_Copied from original issue: tonioo/modoboa#635_

**Comment by tonioo** [comment]
Hi,
this issue has been reported with large mailboxes... Currently, I don't have a quick fix for it.

**Comment by vingeni** [comment]
With the master HEAD version of webmail, I am able to read an inbox with more than 18000 emails.
I also tried to fullfill my inbox with big mails, but in my case, it works.

If somebody reproduce this bug, please, attach a full callstack.

**Comment by vingeni** [comment]
The bug is not reproductible with older versions of python (not reproductible on debian wheezy) and is due to a commit from september 2013 in python imaplib module.

This bug is due to a limitation added on server responses into the python's imaplib module : http://bugs.python.org/issue16039. Now the response line from an imap server must not exeed 10000 bytes. And in a case of a SEARCH or SORT on a mailbox which contains a lot of messages, this limit is reached. 

By reading the IMAP [rfc2683](https://www.ietf.org/rfc/rfc2683.txt) pointed  by the python's issue, I think there is a misinterpretation from team maintaining the imaplib module : the RFC defines this size limitation for clients commands and not for server responses.

The rfc2683 does not define any server response size limitation, it only underlines, in section 3.2.1, the risk that a client may generate requests that results in very large responses (so we are not a bug from dovecot imap server).

If you decide to replace the standard imaplib module with some other, then the new imap module must no rely on the standard imaplib if you want to be sure to not fall again in this bug.

I found two workarounds :

1. You can simply change the default imap._MAXLINE value to a bigger value (e.g: multiply the original value by 10 or 100), At lease, one other opensource project has done it (e.g : [IMAPdedup](https://github.com/quentinsf/IMAPdedup/issues/19)).

2. This response size limitation has only been implemented in the IMAP4.readline function, and not in the IMAP4_SSL.readline, which means, you won't have the bug by using SSL. But then you can fall in the issue16039 the python's team tried to fix.

My suggestions are :
- set imaplib._MAXLINE to 100000,
- open a bug on python imaplib module,
- look for a python imap module, not based on imaplib.

**Comment by vingeni** [comment]
In fact, there is already a discution on this imaplib._MAXLIMIT on the python's team side : http://bugs.python.org/issue23647
So this limitation issue will probably disappear with newer python versions.

**Comment by vingeni** [comment]
the SSL workaround is not anymore present on latest python version (3.4.3), so it is not a good solution.

**Comment by tonioo** [comment]
Many thanks for this explanation!

I think we can begin with a "monkey patch" of the std imaplib (your suggestion). In the future, if we want a better webmail, we will have to implement (or find) a new client.
